### ISSUE TITLE
Error when using remove.py

### ISSUE THREAD

**Issue by sjwhhhi** [JingyuanHu/COCO2VOC#1]
I got the following error.
Could you tell how to solve it? Thank you!

ValueError: Extra data: line 1 column 91865116 - line 1 column 113701974 (char 91865115 - 113701973)

**Comment by JingyuanHu** [comment]
Sorry for replying late. I've tried this code on COCO2014, COCO2017. Never met the problem you had. Maybe you need to check whether the data is completely downloaded
