### ISSUE TITLE
Runtime error json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by KienPM** [JingyuanHu/COCO2VOC#2]
I got "json.decoder.JSONDecodeError: Extra data: line 1 column 15419440 (char 15419439)" when run write.py
```
Traceback (most recent call last):
  File "write.py", line 80, in <module>
    ann_data = json.load(f)
```
Can you help me?

**Comment by JingyuanHu** [comment]
Sorry for replying late. I've tried this code on COCO2014, COCO2017. Never met the problem you had. 
Maybe you can try 

> ann_data = json.load(f,  strict=False) 

rather than 

> ann_data = json.load(f)

**Comment by KienPM** [comment]
thank you, let me try

**Comment by JingyuanHu** [comment]
This issue will be closed cause no more reponse.
